image: node:alpine
pages:
  stage: deploy
  variables:
  PUBLIC_URL: /react-assessment-todo-part-2
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
